# Generated by Django 5.1.2 on 2024-11-05 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar',
            name='temperatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solar',
            name='numero_placas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='valor_energia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='solar',
            name='valor_placa',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
