# Generated by Django 5.1.2 on 2024-11-07 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_solar_temperatura_alter_solar_numero_placas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar',
            name='valor_energia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
